# Generated by Django 5.2 on 2025-07-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profesor",
            name="edad",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
