# Generated by Django 5.2 on 2025-07-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_profesor_edad"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="solo_empresas",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="curso",
            name="turno",
            field=models.CharField(default="M", max_length=1),
        ),
        migrations.AlterField(
            model_name="profesor",
            name="edad",
            field=models.IntegerField(default=0),
        ),
    ]
