# Generated by Django 5.2 on 2025-07-04 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_curso_solo_empresas_curso_turno_alter_profesor_edad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="turno",
            field=models.CharField(
                choices=[("M", "Mañana"), ("T", "Tarde"), ("N", "Noche")], null=True
            ),
        ),
    ]
